// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/libmachete (interfaces: Templates)

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Templates interface
type MockTemplates struct {
	ctrl     *gomock.Controller
	recorder *_MockTemplatesRecorder
}

// Recorder for MockTemplates (not exported)
type _MockTemplatesRecorder struct {
	mock *MockTemplates
}

func NewMockTemplates(ctrl *gomock.Controller) *MockTemplates {
	mock := &MockTemplates{ctrl: ctrl}
	mock.recorder = &_MockTemplatesRecorder{mock}
	return mock
}

func (_m *MockTemplates) EXPECT() *_MockTemplatesRecorder {
	return _m.recorder
}

func (_m *MockTemplates) Read(_param0 string, _param1 string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Read", _param0, _param1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockTemplatesRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Read", arg0, arg1)
}
