// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/codedellemc/infrakit.rackhd/monorail (interfaces: Iface)

package mock

import (
	monorail "github.com/codedellemc/infrakit.rackhd/monorail"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Iface interface
type MockIface struct {
	ctrl     *gomock.Controller
	recorder *_MockIfaceRecorder
}

// Recorder for MockIface (not exported)
type _MockIfaceRecorder struct {
	mock *MockIface
}

func NewMockIface(ctrl *gomock.Controller) *MockIface {
	mock := &MockIface{ctrl: ctrl}
	mock.recorder = &_MockIfaceRecorder{mock}
	return mock
}

func (_m *MockIface) EXPECT() *_MockIfaceRecorder {
	return _m.recorder
}

func (_m *MockIface) Nodes() monorail.NodeIface {
	ret := _m.ctrl.Call(_m, "Nodes")
	ret0, _ := ret[0].(monorail.NodeIface)
	return ret0
}

func (_mr *_MockIfaceRecorder) Nodes() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Nodes")
}
