// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/codedellemc/infrakit.rackhd/monorail (interfaces: SkuIface)

package mock

import (
	skus "github.com/codedellemc/gorackhd/client/skus"
	runtime "github.com/go-openapi/runtime"
	gomock "github.com/golang/mock/gomock"
)

// Mock of SkuIface interface
type MockSkuIface struct {
	ctrl     *gomock.Controller
	recorder *_MockSkuIfaceRecorder
}

// Recorder for MockSkuIface (not exported)
type _MockSkuIfaceRecorder struct {
	mock *MockSkuIface
}

func NewMockSkuIface(ctrl *gomock.Controller) *MockSkuIface {
	mock := &MockSkuIface{ctrl: ctrl}
	mock.recorder = &_MockSkuIfaceRecorder{mock}
	return mock
}

func (_m *MockSkuIface) EXPECT() *_MockSkuIfaceRecorder {
	return _m.recorder
}

func (_m *MockSkuIface) GetSkus(_param0 *skus.GetSkusParams, _param1 runtime.ClientAuthInfoWriter) (*skus.GetSkusOK, error) {
	ret := _m.ctrl.Call(_m, "GetSkus", _param0, _param1)
	ret0, _ := ret[0].(*skus.GetSkusOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSkuIfaceRecorder) GetSkus(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSkus", arg0, arg1)
}

func (_m *MockSkuIface) GetSkusIdentifierNodes(_param0 *skus.GetSkusIdentifierNodesParams, _param1 runtime.ClientAuthInfoWriter) (*skus.GetSkusIdentifierNodesOK, error) {
	ret := _m.ctrl.Call(_m, "GetSkusIdentifierNodes", _param0, _param1)
	ret0, _ := ret[0].(*skus.GetSkusIdentifierNodesOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSkuIfaceRecorder) GetSkusIdentifierNodes(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSkusIdentifierNodes", arg0, arg1)
}
