// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/codedellemc/infrakit.rackhd/monorail (interfaces: NodeIface)

package mock

import (
	nodes "github.com/codedellemc/gorackhd/client/nodes"
	runtime "github.com/go-openapi/runtime"
	gomock "github.com/golang/mock/gomock"
)

// Mock of NodeIface interface
type MockNodeIface struct {
	ctrl     *gomock.Controller
	recorder *_MockNodeIfaceRecorder
}

// Recorder for MockNodeIface (not exported)
type _MockNodeIfaceRecorder struct {
	mock *MockNodeIface
}

func NewMockNodeIface(ctrl *gomock.Controller) *MockNodeIface {
	mock := &MockNodeIface{ctrl: ctrl}
	mock.recorder = &_MockNodeIfaceRecorder{mock}
	return mock
}

func (_m *MockNodeIface) EXPECT() *_MockNodeIfaceRecorder {
	return _m.recorder
}

func (_m *MockNodeIface) GetNodes(_param0 *nodes.GetNodesParams, _param1 runtime.ClientAuthInfoWriter) (*nodes.GetNodesOK, error) {
	ret := _m.ctrl.Call(_m, "GetNodes", _param0, _param1)
	ret0, _ := ret[0].(*nodes.GetNodesOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNodeIfaceRecorder) GetNodes(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetNodes", arg0, arg1)
}
