FROM golang:1.6.1

ENV GOPATH=/go

RUN go get github.com/tools/godep

COPY . /go/src/github.com/docker/libmachete

WORKDIR /go/src/github.com/docker/libmachete/

RUN mkdir -p /build/controller

RUN godep go build -o /build/controller/loadbalancer ./controller/loadbalancer/cmd/*.go
