// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/infrakit/pkg/spi/flavor (interfaces: Plugin)

package flavor

import (
	flavor "github.com/docker/infrakit/pkg/spi/flavor"
	types0 "github.com/docker/infrakit/pkg/spi/group"
	instance "github.com/docker/infrakit/pkg/spi/instance"
	types "github.com/docker/infrakit/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Plugin interface
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *_MockPluginRecorder
}

// Recorder for MockPlugin (not exported)
type _MockPluginRecorder struct {
	mock *MockPlugin
}

func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &_MockPluginRecorder{mock}
	return mock
}

func (_m *MockPlugin) EXPECT() *_MockPluginRecorder {
	return _m.recorder
}

func (_m *MockPlugin) Drain(_param0 *types.Any, _param1 instance.Description) error {
	ret := _m.ctrl.Call(_m, "Drain", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPluginRecorder) Drain(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Drain", arg0, arg1)
}

func (_m *MockPlugin) Healthy(_param0 *types.Any, _param1 instance.Description) (flavor.Health, error) {
	ret := _m.ctrl.Call(_m, "Healthy", _param0, _param1)
	ret0, _ := ret[0].(flavor.Health)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPluginRecorder) Healthy(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Healthy", arg0, arg1)
}

func (_m *MockPlugin) Prepare(_param0 *types.Any, _param1 instance.Spec, _param2 types0.AllocationMethod, _param3 types0.Index) (instance.Spec, error) {
	ret := _m.ctrl.Call(_m, "Prepare", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(instance.Spec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPluginRecorder) Prepare(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Prepare", arg0, arg1, arg2, arg3)
}

func (_m *MockPlugin) Validate(_param0 *types.Any, _param1 types0.AllocationMethod) error {
	ret := _m.ctrl.Call(_m, "Validate", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPluginRecorder) Validate(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate", arg0, arg1)
}
