// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/infrakit.gcp/plugin/gcloud (interfaces: APIMetadata)

package gcloud

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of APIMetadata interface
type MockAPIMetadata struct {
	ctrl     *gomock.Controller
	recorder *_MockAPIMetadataRecorder
}

// Recorder for MockAPIMetadata (not exported)
type _MockAPIMetadataRecorder struct {
	mock *MockAPIMetadata
}

func NewMockAPIMetadata(ctrl *gomock.Controller) *MockAPIMetadata {
	mock := &MockAPIMetadata{ctrl: ctrl}
	mock.recorder = &_MockAPIMetadataRecorder{mock}
	return mock
}

func (_m *MockAPIMetadata) EXPECT() *_MockAPIMetadataRecorder {
	return _m.recorder
}

func (_m *MockAPIMetadata) GetHostname() (string, error) {
	ret := _m.ctrl.Call(_m, "GetHostname")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAPIMetadataRecorder) GetHostname() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHostname")
}
