FROM alpine:3.5

RUN apk add --update ca-certificates

RUN mkdir -p /infrakit/plugins /infrakit/configs /infrakit/logs /infrakit/cli

VOLUME /infrakit

ENV INFRAKIT_HOME /infrakit
ENV INFRAKIT_PLUGINS_DIR /infrakit/plugins
ENV INFRAKIT_CLI_DIR /infrakit/cli

ADD build/* /usr/local/bin/
