FROM golang:1.7.1-alpine

# A simple container for compiling Go projects with govendor and misc tools

MAINTAINER chungers <david.chung@docker.com>

RUN apk add --update git tree make

env GOPATH=/go
env PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN go get github.com/kardianos/govendor
RUN go get github.com/golang/lint/golint
RUN go get github.com/golang/mock/gomock
RUN go get github.com/golang/mock/mockgen