FROM alpine:3.4

# InfraKit.aws bundle: for AWS instance drivers
# OSS - Use at your own risk - see project LICENSE for details

MAINTAINER David Chung <david.chung@docker.com>

RUN apk add --update ca-certificates && rm -Rf /tmp/* /var/lib/cache/apk/*
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

ADD build/* /usr/local/bin/
