FROM golang:1.7.5-alpine

RUN apk add --update git make
RUN go get github.com/rancher/trash

WORKDIR /go/src/github.com/docker/infrakit
VOLUME [ "/go/src/github.com/docker/infrakit/build" ]
CMD make build-binaries

COPY . ./
RUN trash  # Force updating the vendored sources per spec; this slows the build but is most correct.
