FROM golang:1.8-alpine

RUN apk add --update git make gcc musl-dev wget ca-certificates openssl libvirt-dev git

ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN go get github.com/docker/infrakit/cmd/infrakit

COPY dockerfiles/build-infrakit /usr/local/bin/
COPY dockerfiles/build-hyperkit /usr/local/bin/
