// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/libmachete/provisioners/spi (interfaces: Provisioner)

package api

import (
	spi "github.com/docker/libmachete/provisioners/spi"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Provisioner interface
type MockProvisioner struct {
	ctrl     *gomock.Controller
	recorder *_MockProvisionerRecorder
}

// Recorder for MockProvisioner (not exported)
type _MockProvisionerRecorder struct {
	mock *MockProvisioner
}

func NewMockProvisioner(ctrl *gomock.Controller) *MockProvisioner {
	mock := &MockProvisioner{ctrl: ctrl}
	mock.recorder = &_MockProvisionerRecorder{mock}
	return mock
}

func (_m *MockProvisioner) EXPECT() *_MockProvisionerRecorder {
	return _m.recorder
}

func (_m *MockProvisioner) CreateInstance(_param0 spi.MachineRequest) (<-chan spi.CreateInstanceEvent, error) {
	ret := _m.ctrl.Call(_m, "CreateInstance", _param0)
	ret0, _ := ret[0].(<-chan spi.CreateInstanceEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProvisionerRecorder) CreateInstance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateInstance", arg0)
}

func (_m *MockProvisioner) DestroyInstance(_param0 string) (<-chan spi.DestroyInstanceEvent, error) {
	ret := _m.ctrl.Call(_m, "DestroyInstance", _param0)
	ret0, _ := ret[0].(<-chan spi.DestroyInstanceEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProvisionerRecorder) DestroyInstance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DestroyInstance", arg0)
}

func (_m *MockProvisioner) GetIPAddress(_param0 spi.MachineRequest) (string, error) {
	ret := _m.ctrl.Call(_m, "GetIPAddress", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProvisionerRecorder) GetIPAddress(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetIPAddress", arg0)
}

func (_m *MockProvisioner) GetInstanceID(_param0 spi.MachineRequest) (string, error) {
	ret := _m.ctrl.Call(_m, "GetInstanceID", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProvisionerRecorder) GetInstanceID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetInstanceID", arg0)
}

func (_m *MockProvisioner) GetProvisionTasks() []spi.Task {
	ret := _m.ctrl.Call(_m, "GetProvisionTasks")
	ret0, _ := ret[0].([]spi.Task)
	return ret0
}

func (_mr *_MockProvisionerRecorder) GetProvisionTasks() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetProvisionTasks")
}

func (_m *MockProvisioner) GetTeardownTasks() []spi.Task {
	ret := _m.ctrl.Call(_m, "GetTeardownTasks")
	ret0, _ := ret[0].([]spi.Task)
	return ret0
}

func (_mr *_MockProvisionerRecorder) GetTeardownTasks() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetTeardownTasks")
}
