// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/libmachete/provisioners (interfaces: Creator)

package mock

import (
	api "github.com/docker/libmachete/provisioners/api"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Creator interface
type MockCreator struct {
	ctrl     *gomock.Controller
	recorder *_MockCreatorRecorder
}

// Recorder for MockCreator (not exported)
type _MockCreatorRecorder struct {
	mock *MockCreator
}

func NewMockCreator(ctrl *gomock.Controller) *MockCreator {
	mock := &MockCreator{ctrl: ctrl}
	mock.recorder = &_MockCreatorRecorder{mock}
	return mock
}

func (_m *MockCreator) EXPECT() *_MockCreatorRecorder {
	return _m.recorder
}

func (_m *MockCreator) Create(_param0 map[string]string) (api.Provisioner, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0)
	ret0, _ := ret[0].(api.Provisioner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCreatorRecorder) Create(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0)
}
