// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/libmachete/provisioners (interfaces: ProvisionerBuilder)

package mock

import (
	api "github.com/docker/libmachete/provisioners/api"
	gomock "github.com/golang/mock/gomock"
)

// Mock of ProvisionerBuilder interface
type MockProvisionerBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockProvisionerBuilderRecorder
}

// Recorder for MockProvisionerBuilder (not exported)
type _MockProvisionerBuilderRecorder struct {
	mock *MockProvisionerBuilder
}

func NewMockProvisionerBuilder(ctrl *gomock.Controller) *MockProvisionerBuilder {
	mock := &MockProvisionerBuilder{ctrl: ctrl}
	mock.recorder = &_MockProvisionerBuilderRecorder{mock}
	return mock
}

func (_m *MockProvisionerBuilder) EXPECT() *_MockProvisionerBuilderRecorder {
	return _m.recorder
}

func (_m *MockProvisionerBuilder) Build(_param0 map[string]string) (api.Provisioner, error) {
	ret := _m.ctrl.Call(_m, "Build", _param0)
	ret0, _ := ret[0].(api.Provisioner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProvisionerBuilderRecorder) Build(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Build", arg0)
}
