# vim:set ft=ruby
Vagrant.configure("2") do |config|
    config.vm.box = "rackhd/rackhd"
    config.vm.box_version = "1.3.0"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.network "private_network", ip: "172.31.128.1", virtualbox__intnet: "closednet", auto_config: false, nic_type: "82540EM"
    config.vm.network "forwarded_port", guest: 8080, host: 9090
    config.vm.network "forwarded_port", guest: 5672, host: 9091
    config.vm.network "forwarded_port", guest: 9080, host: 9092
    config.vm.network "forwarded_port", guest: 8443, host: 9093
    config.vm.network "forwarded_port", guest: 7080, host: 6080

    # If true, then any SSH connections made will enable agent forwarding.
    # Default value: false

    config.ssh.forward_agent = true

    config.vm.provision "shell", inline: <<-EOS
      /usr/bin/apt-get install -y gccgo-go
      /usr/bin/curl -sk -H "Content-Type: application/json" -X POST https://localhost:8443/api/current/users -d '{"username": "admin", "password": "admin123", "role": "Administrator"}'
    EOS
    #   git clone https://github.com/docker/infrakit.git
    #   cd infrakit
    #   make binaries
    #   build/infrakit-group-default &
    #   build/infrakit-flavor-vanilla &
end
