#!/bin/sh

# Installs infrakit by cross compiling locally inside a docker container.

if [ "$(which docker)" = "" ]; then
    echo "You must have Docker locally."
    exit -1
fi

dir=$(pwd)
case "$(uname)" in
    Darwin)
	export target="darwin"
	;;
    Linux)
	export target="linux"
	;;
    *)
	echo "not supported: $(uname)"
	exit -1
	;;
esac

echo "Building infrakit..."
docker run --name install_infrakit infrakit/installer:latest build-infrakit $target
echo "Copying to /usr/local/bin via sudo..."
sudo docker cp install_infrakit:/build/infrakit /usr/local/bin
echo "Clean up installer..."
docker rm install_infrakit && docker image rm infrakit/installer:latest
