package aws

import (
	"github.com/aws/aws-sdk-go/service/ec2"
	"github.com/docker/libmachete/api"
	"github.com/docker/libmachete/provisioners/spi"
)

// generateAndUploadSSHKey overrides the default SSHKeyGen task to first generate the key then upload to EC2.
// It also mutates the input request to use the generated key.
func (p provisioner) generateAndUploadSSHKey(
	resource spi.Resource,
	request spi.MachineRequest,
	events chan<- interface{}) error {

	createInstanceRequest, err := ensureRequestType(request)
	if err != nil {
		return err
	}

	// Call the default implementation to generate the key
	if err := api.SSHKeyGen(p.sshKeys).Do(resource, request, events); err != nil {
		return err
	}

	keyName := resource.Name()
	publicKey, err := p.sshKeys.GetEncodedPublicKey(api.SSHKeyID(keyName))
	if err != nil {
		events <- err
		return err
	}

	// AWS requires that the key be uploaded prior to creating the instance
	_, err = p.client.ImportKeyPair(&ec2.ImportKeyPairInput{KeyName: &keyName, PublicKeyMaterial: publicKey})
	if err != nil {
		return err
	}

	// Now we have successfully imported the key, change the input to use this
	createInstanceRequest.KeyName = keyName

	// Send this change to be logged.
	events <- createInstanceRequest
	return nil
}

// removeLocalAndUploadedSSHKey removes the local ssh key and calls EC2 api to remove the uploaded key.
// TODO(chungers) - consider splitting this into two separate tasks so that we can
// support shared key generated by this framework.
func (p provisioner) removeLocalAndUploadedSSHKey(
	resource spi.Resource,
	request spi.MachineRequest,
	events chan<- interface{}) error {

	keyName := resource.Name()

	// AWS requires that the key be uploaded prior to creating the instance
	_, err := p.client.DeleteKeyPair(&ec2.DeleteKeyPairInput{KeyName: &keyName})
	if err != nil {
		return err
	}

	// Call the default implementation to generate the key
	if err := api.SSHKeyRemove(p.sshKeys).Do(resource, request, events); err != nil {
		return err
	}

	return nil
}
