// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/libmachete/plugin/group/util (interfaces: Executor)

package updater

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Executor interface
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *_MockExecutorRecorder
}

// Recorder for MockExecutor (not exported)
type _MockExecutorRecorder struct {
	mock *MockExecutor
}

func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &_MockExecutorRecorder{mock}
	return mock
}

func (_m *MockExecutor) EXPECT() *_MockExecutorRecorder {
	return _m.recorder
}

func (_m *MockExecutor) Proceed() {
	_m.ctrl.Call(_m, "Proceed")
}

func (_mr *_MockExecutorRecorder) Proceed() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Proceed")
}
